name: Docker Image CI - latest

on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: mr-smithers-excellent/docker-build-push@v1.0
        with:
          image: satont/twobit/master
          tag: latest 
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
